name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      CI_TOOLS: ./ci-tools
      ARTIFACTORY_USERNAME: sean.mcbrien
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      
    steps:
    
    - name: Checkout this repo
      uses: actions/checkout@v2
      
    - name: Checkout build tools repo
      uses: actions/checkout@v2
      with:
        repository:  seanmcb-smarsh/forked-build-tools 
        path: ci-tools
        
    - name: Docker Login
      run: ./ci-tools/package docker_login
    
    - name: Build
      run: ./ci-tools/package-all.sh
